version: '3.9'
services:
  nodejs:
    container_name: nodejs-container
    restart: unless-stopped
    build: .
    env_file: .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
    ports:
      - "3003:3003"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-container
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
    

    